apply plugin: 'com.android.application'

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'org.liberty.android.nc1020emu'
    compileSdk 35
    ndkVersion "29.0.14206865"

    defaultConfig {
        minSdk 21
        targetSdk 35
        versionCode 2
        versionName "1.1"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
        }
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "androidx.navigation:navigation-fragment-ktx:2.7.7"
    implementation "androidx.navigation:navigation-ui-ktx:2.7.7"
    implementation "androidx.preference:preference-ktx:1.2.1"
    implementation "androidx.core:core-ktx:1.13.1"
    implementation 'com.google.android.material:material:1.12.0'
}

