/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_liberty_android_nc1020emu_NC1020_JNI */

#ifndef _Included_org_liberty_android_nc1020emu_NC1020_JNI
#define _Included_org_liberty_android_nc1020emu_NC1020_JNI
/*
 * Class:     org_liberty_android_nc1020emu_NC1020_JNI
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_liberty_android_nc1020emu_NC1020JNI_initialize
  (JNIEnv *, jclass , jstring);

/*
 * Class:     org_liberty_android_nc1020emu_NC1020_JNI
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_liberty_android_nc1020emu_NC1020JNI_reset
  (JNIEnv *, jclass);

/*
 * Class:     org_liberty_android_nc1020emu_NC1020_JNI
 * Method:    load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_liberty_android_nc1020emu_NC1020JNI_load
  (JNIEnv *, jclass);

/*
 * Class:     org_liberty_android_nc1020emu_NC1020_JNI
 * Method:    save
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_liberty_android_nc1020emu_NC1020JNI_save
  (JNIEnv *, jclass);

/*
 * Class:     org_liberty_android_nc1020emu_NC1020_JNI
 * Method:    set_key
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_liberty_android_nc1020emu_NC1020JNI_setKey
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_liberty_android_nc1020emu_NC1020_JNI
 * Method:    run_time_slice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_liberty_android_nc1020emu_NC1020JNI_runTimeSlice
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_liberty_android_nc1020emu_NC1020_JNI
 * Method:    copy_lcd_buffer
 * Signature: ([C)V
 */
JNIEXPORT jboolean JNICALL Java_org_liberty_android_nc1020emu_NC1020JNI_copyLcdBuffer
  (JNIEnv *, jobject, jbyteArray);
#endif
