/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_liberty_android_nc1020emu_NC1020_JNI */

#ifndef _Included_org_liberty_android_nc1020emu_NC1020_JNI
#define _Included_org_liberty_android_nc1020emu_NC1020_JNI
/*
 * Class:     org_liberty_android_nc1020emu_NC1020_JNI
 * Method:    Initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_liberty_android_nc1020emu_NC1020JNI_Initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_liberty_android_nc1020emu_NC1020_JNI
 * Method:    Reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_liberty_android_nc1020emu_NC1020JNI_Reset
  (JNIEnv *, jobject);

/*
 * Class:     org_liberty_android_nc1020emu_NC1020_JNI
 * Method:    Load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_liberty_android_nc1020emu_NC1020JNI_Load
  (JNIEnv *, jobject);

/*
 * Class:     org_liberty_android_nc1020emu_NC1020_JNI
 * Method:    Save
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_liberty_android_nc1020emu_NC1020JNI_Save
  (JNIEnv *, jobject);

/*
 * Class:     org_liberty_android_nc1020emu_NC1020_JNI
 * Method:    SetKey
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_liberty_android_nc1020emu_NC1020JNI_SetKey
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_liberty_android_nc1020emu_NC1020_JNI
 * Method:    RunTimeSlice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_liberty_android_nc1020emu_NC1020JNI_RunTimeSlice
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_liberty_android_nc1020emu_NC1020_JNI
 * Method:    CopyLcdBuffer
 * Signature: ([C)V
 */
JNIEXPORT jboolean JNICALL Java_org_liberty_android_nc1020emu_NC1020JNI_CopyLcdBuffer
  (JNIEnv *, jobject, jbyteArray);
#endif
